#	1. Compose (plug-in-compose)
#	2. Gradient Map (gimp-context-set-gradient, plug-in-gradmap)
(define (gimp-heatmap	filename)
	(let* ((image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
			(drawable (car (gimp-image-get-active-layer image))))
		(plug-in-compose RUN-NONINTERACTIVE image drawable image image image "RGB")
		(gimp-context-set-gradient "Custom1")
		(plug-in-gradmap RUN-NONINTERACTIVE image drawable)
		(gimp-file-save RUN-NONINTERACTIVE image drawable ("c_"filename) ("c_"filename))

